import {
  Client,
  Campaign,
  ProofPack,
  Metric,
  DemoUser,
  RecentActivityItem,
  Stats,
  ChartData,
  SparklineData,
} from './types';

// Helper to generate UUIDs for mock data
const generateId = (): string => Math.random().toString(36).substring(2, 15);

// Helper to generate ISO date strings
const getPastDate = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

const getRecentDateTime = (minutesAgo: number): string => {
  const date = new Date();
  date.setMinutes(date.getMinutes() - minutesAgo);
  return date.toISOString();
};

export const DEMO_USER: DemoUser = {
  id: 'usr_j8k3l4m5n6p7q8r9s0',
  name: 'Marcus Webb',
  email: 'marcus.webb@agencyco.com',
  role: 'Agency Owner',
  plan: 'Pro Plan',
  avatar: 'MW',
  joinedAt: getPastDate(730), // 2 years ago
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'clt_101',
    name: 'Innovate Solutions',
    contactEmail: 'contact@innovatesol.com',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 30), // 30 days ago
    updatedAt: getRecentDateTime(1440 * 5),
  },
  {
    id: 'clt_102',
    name: 'Growth Metrics Ltd.',
    contactEmail: 'info@growthmetrics.co',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 45),
    updatedAt: getRecentDateTime(1440 * 10),
  },
  {
    id: 'clt_103',
    name: 'Digital Dynamics Inc.',
    contactEmail: 'sales@digitaldynamics.net',
    status: 'inactive',
    createdAt: getRecentDateTime(1440 * 60),
    updatedAt: getRecentDateTime(1440 * 20),
  },
  {
    id: 'clt_104',
    name: 'Future Innovations',
    contactEmail: 'hello@futureinnov.com',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 90),
    updatedAt: getRecentDateTime(1440 * 15),
  },
  {
    id: 'clt_105',
    name: 'Alpha Marketing Group',
    contactEmail: 'connect@alphamarketing.biz',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 120),
    updatedAt: getRecentDateTime(1440 * 2),
  },
  {
    id: 'clt_106',
    name: 'Synergy Brands',
    contactEmail: 'partners@synergybrands.org',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 150),
    updatedAt: getRecentDateTime(1440 * 7),
  },
  {
    id: 'clt_107',
    name: 'Elite Campaigns',
    contactEmail: 'support@elitecampaigns.io',
    status: 'inactive',
    createdAt: getRecentDateTime(1440 * 180),
    updatedAt: getRecentDateTime(1440 * 25),
  },
  {
    id: 'clt_108',
    name: 'Brand Builders Co.',
    contactEmail: 'contact@brandbuilders.com',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 210),
    updatedAt: getRecentDateTime(1440 * 3),
  },
  {
    id: 'clt_109',
    name: 'Lead Generation Pro',
    contactEmail: 'info@leadgenpro.net',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 240),
    updatedAt: getRecentDateTime(1440 * 1),
  },
  {
    id: 'clt_110',
    name: 'Content King Agency',
    contactEmail: 'editor@contentking.com',
    status: 'archived',
    createdAt: getRecentDateTime(1440 * 270),
    updatedAt: getRecentDateTime(1440 * 40),
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp_201',
    clientId: 'clt_101',
    title: 'Q1 2024 Conversion Boost',
    description: 'Focus on improving conversion rates through retargeting and funnel optimization.',
    startDate: getPastDate(90),
    endDate: getPastDate(30),
    objective: 'Increase MQL to SQL conversion by 15%',
    status: 'completed',
    createdAt: getRecentDateTime(1440 * 100),
    updatedAt: getRecentDateTime(1440 * 5),
  },
  {
    id: 'cmp_202',
    clientId: 'clt_102',
    title: 'Brand Awareness Push H1 2024',
    description: 'Broad reach campaign across social media and display networks.',
    startDate: getPastDate(120),
    endDate: getPastDate(60),
    objective: 'Achieve 5M impressions and 50k brand mentions',
    status: 'completed',
    createdAt: getRecentDateTime(1440 * 130),
    updatedAt: getRecentDateTime(1440 * 12),
  },
  {
    id: 'cmp_203',
    clientId: 'clt_101',
    title: 'New Product Launch - Spring 2024',
    description: 'Multi-channel launch for Innovate Solutions new SaaS product.',
    startDate: getPastDate(45),
    endDate: getPastDate(5),
    objective: 'Drive 1000 sign-ups in first month',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 50),
    updatedAt: getRecentDateTime(1440 * 1),
  },
  {
    id: 'cmp_204',
    clientId: 'clt_104',
    title: 'Winter Lead Gen 2023-2024',
    description: 'B2B lead generation via LinkedIn and content syndication.',
    startDate: getPastDate(180),
    endDate: getPastDate(90),
    objective: 'Generate 250 qualified leads',
    status: 'completed',
    createdAt: getRecentDateTime(1440 * 190),
    updatedAt: getRecentDateTime(1440 * 8),
  },
  {
    id: 'cmp_205',
    clientId: 'clt_105',
    title: 'Website Redesign & SEO Boost',
    description: 'Technical SEO improvements and content refresh.',
    startDate: getPastDate(70),
    endDate: getPastDate(10),
    objective: 'Improve organic traffic by 30%',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 80),
    updatedAt: getRecentDateTime(1440 * 3),
  },
  {
    id: 'cmp_206',
    clientId: 'clt_106',
    title: 'Social Media Engagement Drive',
    description: 'Campaign focused on increasing social media interactions.',
    startDate: getPastDate(60),
    endDate: getPastDate(1),
    objective: 'Increase engagement rate by 2%',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 70),
    updatedAt: getRecentDateTime(1440 * 0.5),
  },
  {
    id: 'cmp_207',
    clientId: 'clt_108',
    title: 'Google Ads Refinement Q2',
    description: 'Optimization of existing Google Ads campaigns.',
    startDate: getPastDate(40),
    endDate: getPastDate(2),
    objective: 'Reduce CPA by 10%',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 45),
    updatedAt: getRecentDateTime(1440 * 0.2),
  },
  {
    id: 'cmp_208',
    clientId: 'clt_109',
    title: 'Email Marketing Nurture Sequence',
    description: 'Automated email sequence for new subscribers.',
    startDate: getPastDate(150),
    endDate: getPastDate(70),
    objective: 'Achieve 20% open rate and 3% click-through',
    status: 'completed',
    createdAt: getRecentDateTime(1440 * 160),
    updatedAt: getRecentDateTime(1440 * 15),
  },
  {
    id: 'cmp_209',
    clientId: 'clt_102',
    title: 'Summer Sale Promotion',
    description: 'Targeted ads for seasonal product sales.',
    startDate: getPastDate(20),
    endDate: getPastDate(1),
    objective: 'Increase online sales by 25%',
    status: 'active',
    createdAt: getRecentDateTime(1440 * 25),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: 'cmp_210',
    clientId: 'clt_105',
    title: 'Content Marketing Strategy H2',
    description: 'Developing pillar content and blog series.',
    startDate: getPastDate(10),
    endDate: getPastDate(-60), // Future end date
    objective: 'Publish 10 new articles, increase blog traffic',
    status: 'paused',
    createdAt: getRecentDateTime(1440 * 15),
    updatedAt: getRecentDateTime(1440 * 0.8),
  },
];

export const MOCK_PROOF_PACKS: ProofPack[] = [
  {
    id: 'pp_301',
    clientId: 'clt_101',
    campaignIds: ['cmp_201'],
    title: 'Innovate Solutions Q1 2024 Performance Review',
    description: 'Comprehensive review of Q1 conversion campaigns.',
    overviewNotes: 'Client expressed interest in deeper insights on retargeting ROI. Focus on granular metric breakdown.',
    status: 'client-ready',
    priority: 'High',
    dueDate: getPastDate(10),
    generatedUrl: 'https://proofpacks.io/reports/pp_301',
    createdAt: getRecentDateTime(1440 * 20),
    updatedAt: getRecentDateTime(1440 * 0.5),
  },
  {
    id: 'pp_302',
    clientId: 'clt_102',
    campaignIds: ['cmp_202'],
    title: 'Growth Metrics H1 2024 Brand Awareness Report',
    description: 'Summary of brand awareness campaign outcomes.',
    overviewNotes: 'Highlight significant impression reach and key engagement trends. Compare against industry benchmarks.',
    status: 'review',
    priority: 'Medium',
    dueDate: getPastDate(5),
    createdAt: getRecentDateTime(1440 * 25),
    updatedAt: getRecentDateTime(1440 * 2),
  },
  {
    id: 'pp_303',
    clientId: 'clt_101',
    campaignIds: ['cmp_203'],
    title: 'Innovate Solutions New Product Launch Summary',
    description: 'Initial performance report for the new SaaS product launch.',
    overviewNotes: 'Detailed breakdown of sign-up sources and initial conversion funnel performance.',
    status: 'draft',
    priority: 'High',
    dueDate: getPastDate(-5), // Due in 5 days
    createdAt: getRecentDateTime(1440 * 3),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: 'pp_304',
    clientId: 'clt_104',
    campaignIds: ['cmp_204'],
    title: 'Future Innovations Winter Lead Gen Outcomes',
    description: 'Report on qualified leads generated over the winter period.',
    overviewNotes: 'Emphasize the quality of leads and pipeline impact. Include cost per lead analysis.',
    status: 'client-ready',
    priority: 'Medium',
    dueDate: getPastDate(20),
    generatedUrl: 'https://proofpacks.io/reports/pp_304',
    createdAt: getRecentDateTime(1440 * 30),
    updatedAt: getRecentDateTime(1440 * 8),
  },
  {
    id: 'pp_305',
    clientId: 'clt_105',
    campaignIds: ['cmp_205'],
    title: 'Alpha Marketing Website SEO Audit & Performance',
    description: 'Review of SEO improvements and organic traffic growth.',
    overviewNotes: 'Show before/after metrics for critical keywords and page load times.',
    status: 'review',
    priority: 'High',
    dueDate: getPastDate(2),
    createdAt: getRecentDateTime(1440 * 7),
    updatedAt: getRecentDateTime(1440 * 0.8),
  },
  {
    id: 'pp_306',
    clientId: 'clt_106',
    campaignIds: ['cmp_206'],
    title: 'Synergy Brands Social Media Engagement Report',
    description: 'Analysis of recent social media campaign engagement.',
    overviewNotes: 'Focus on platform-specific engagement rates and audience sentiment.',
    status: 'draft',
    priority: 'Low',
    dueDate: getPastDate(-10), // Due in 10 days
    createdAt: getRecentDateTime(1440 * 1),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: 'pp_307',
    clientId: 'clt_108',
    campaignIds: ['cmp_207'],
    title: 'Brand Builders Q2 Google Ads Optimization',
    description: 'Performance summary of Google Ads refinements.',
    overviewNotes: 'Highlight CPA reductions and improved ad relevance scores.',
    status: 'review',
    priority: 'High',
    dueDate: getPastDate(1),
    createdAt: getRecentDateTime(1440 * 2),
    updatedAt: getRecentDateTime(1440 * 0.2),
  },
  {
    id: 'pp_308',
    clientId: 'clt_109',
    campaignIds: ['cmp_208'],
    title: 'Lead Generation Pro Email Nurture Sequence Results',
    description: 'Report on the effectiveness of the email marketing funnel.',
    overviewNotes: 'Show funnel conversion rates and key email performance metrics.',
    status: 'archived',
    priority: 'Low',
    dueDate: getPastDate(90),
    generatedUrl: 'https://proofpacks.io/reports/pp_308',
    createdAt: getRecentDateTime(1440 * 100),
    updatedAt: getRecentDateTime(1440 * 30),
  },
  {
    id: 'pp_309',
    clientId: 'clt_102',
    campaignIds: ['cmp_209'],
    title: 'Growth Metrics Summer Sale Promo Report',
    description: 'Detailed report on sales performance during the summer promotion.',
    overviewNotes: 'Breakdown sales by product category and channel. Analyze discount effectiveness.',
    status: 'draft',
    priority: 'High',
    dueDate: getPastDate(-3), // Due in 3 days
    createdAt: getRecentDateTime(1440 * 0.5),
    updatedAt: getRecentDateTime(1440 * 0.05),
  },
  {
    id: 'pp_310',
    clientId: 'clt_105',
    campaignIds: ['cmp_210'],
    title: 'Alpha Marketing H2 Content Strategy Kick-off',
    description: 'Initial planning and content production progress.',
    overviewNotes: 'Outline content calendar, keyword research, and initial article drafts.',
    status: 'review',
    priority: 'Medium',
    dueDate: getPastDate(-20), // Due in 20 days
    createdAt: getRecentDateTime(1440 * 1),
    updatedAt: getRecentDateTime(1440 * 0.2),
  },
];

export const MOCK_METRICS: Metric[] = [
  {
    id: generateId(),
    proofPackId: 'pp_301',
    campaignId: 'cmp_201',
    name: 'Ad Spend',
    value: 12500.75,
    unit: '$',
    date: getPastDate(20),
    notes: 'Total spend across Google Ads and Meta platforms.',
    createdAt: getRecentDateTime(1440 * 19),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: generateId(),
    proofPackId: 'pp_301',
    campaignId: 'cmp_201',
    name: 'Conversions',
    value: 320,
    unit: 'leads',
    date: getPastDate(20),
    notes: 'Website form submissions and direct calls.',
    createdAt: getRecentDateTime(1440 * 19),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: generateId(),
    proofPackId: 'pp_301',
    campaignId: 'cmp_201',
    name: 'Conversion Rate',
    value: 2.5,
    unit: '%',
    date: getPastDate(20),
    notes: 'Calculated from unique clicks.',
    createdAt: getRecentDateTime(1440 * 19),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: generateId(),
    proofPackId: 'pp_302',
    campaignId: 'cmp_202',
    name: 'Impressions',
    value: 4800000,
    unit: '',
    date: getPastDate(15),
    notes: 'Total impressions across all channels.',
    createdAt: getRecentDateTime(1440 * 14),
    updatedAt: getRecentDateTime(1440 * 0.5),
  },
  {
    id: generateId(),
    proofPackId: 'pp_302',
    campaignId: 'cmp_202',
    name: 'Brand Mentions',
    value: 48900,
    unit: '',
    date: getPastDate(15),
    notes: 'Tracked via social listening tools.',
    createdAt: getRecentDateTime(1440 * 14),
    updatedAt: getRecentDateTime(1440 * 0.5),
  },
  {
    id: generateId(),
    proofPackId: 'pp_303',
    campaignId: 'cmp_203',
    name: 'Sign-ups',
    value: 850,
    unit: '',
    date: getPastDate(2),
    notes: 'New user registrations for the SaaS product.',
    createdAt: getRecentDateTime(1440 * 1),
    updatedAt: getRecentDateTime(1440 * 0.05),
  },
  {
    id: generateId(),
    proofPackId: 'pp_304',
    campaignId: 'cmp_204',
    name: 'Qualified Leads',
    value: 230,
    unit: '',
    date: getPastDate(25),
    notes: 'Leads scored BANT-qualified by sales team.',
    createdAt: getRecentDateTime(1440 * 24),
    updatedAt: getRecentDateTime(1440 * 1.5),
  },
  {
    id: generateId(),
    proofPackId: 'pp_305',
    campaignId: 'cmp_205',
    name: 'Organic Traffic',
    value: 35.2,
    unit: '% increase',
    date: getPastDate(7),
    notes: 'Measured by Google Analytics comparison period.',
    createdAt: getRecentDateTime(1440 * 6),
    updatedAt: getRecentDateTime(1440 * 0.2),
  },
  {
    id: generateId(),
    proofPackId: 'pp_307',
    campaignId: 'cmp_207',
    name: 'Cost Per Acquisition (CPA)',
    value: 18.25,
    unit: '$',
    date: getPastDate(0),
    notes: 'Decreased by 12% from previous period.',
    createdAt: getRecentDateTime(1440 * 0.1),
    updatedAt: getRecentDateTime(1440 * 0.01),
  },
  {
    id: generateId(),
    proofPackId: 'pp_309',
    campaignId: 'cmp_209',
    name: 'Online Sales',
    value: 15.8,
    unit: '% increase',
    date: getPastDate(0),
    notes: 'Compared to sales during a non-promotional period.',
    createdAt: getRecentDateTime(1440 * 0.05),
    updatedAt: getRecentDateTime(1440 * 0.005),
  },
  {
    id: generateId(),
    proofPackId: 'pp_301',
    campaignId: 'cmp_201',
    name: 'Cost Per Click (CPC)',
    value: 1.15,
    unit: '$',
    date: getPastDate(20),
    notes: 'Average CPC across all paid channels.',
    createdAt: getRecentDateTime(1440 * 19),
    updatedAt: getRecentDateTime(1440 * 0.1),
  },
  {
    id: generateId(),
    proofPackId: 'pp_303',
    campaignId: 'cmp_203',
    name: 'Trial Conversions',
    value: 55,
    unit: '',
    date: getPastDate(2),
    notes: 'Number of sign-ups converting to paying customers within 7 days.',
    createdAt: getRecentDateTime(1440 * 1),
    updatedAt: getRecentDateTime(1440 * 0.05),
  },
];


export const STATS: Stats = {
  totalProofPacks: 10,
  clientReadyPacks: 3,
  packsInReview: 4,
  draftPacks: 3,
  avgTimeToClientReady: '7 days',
  totalClientsManaged: 8, // Active clients
};

export const CHART_DATA: ChartData = {
  weekly: [42, 58, 51, 73, 88, 65, 79, 94, 71, 103, 89, 112],
  labels: ['Jan W1', 'Jan W2', 'Feb W1', 'Feb W2', 'Mar W1', 'Mar W2', 'Apr W1', 'Apr W2', 'May W1', 'May W2', 'Jun W1', 'Jun W2'],
  proofPacksCreated: [5, 7, 6, 8, 9, 7, 8, 10, 8, 11, 9, 12],
  clientReadyPacks: [2, 3, 2, 4, 3, 3, 4, 5, 4, 6, 5, 6],
};

export const SPARKLINE_DATA: SparklineData = {
  totalProofPacks: [8, 9, 8, 10, 9, 10, 10],
  clientReadyPacks: [2, 2, 3, 3, 3, 3, 3],
  packsInReview: [3, 4, 3, 4, 4, 4, 4],
  draftPacks: [3, 3, 2, 3, 2, 3, 3],
};

export const RECENT_ACTIVITY: RecentActivityItem[] = [
  { id: 'act_001', action: 'Created new Proof Pack: Innovate Solutions New Product Launch Summary', user: 'Marcus Webb', avatar: 'MW', time: '5 minutes ago', type: 'create' },
  { id: 'act_002', action: 'Updated Proof Pack: Alpha Marketing Website SEO Audit & Performance', user: 'Sarah Chen', avatar: 'SC', time: '15 minutes ago', type: 'update' },
  { id: 'act_003', action: 'Changed status of Growth Metrics H1 2024 Brand Awareness Report to \'review\'', user: 'Marcus Webb', avatar: 'MW', time: '30 minutes ago', type: 'status-change' },
  { id: 'act_004', action: 'Added new metrics to Proof Pack: Innovate Solutions Q1 2024 Performance Review', user: 'David Lee', avatar: 'DL', time: '1 hour ago', type: 'update' },
  { id: 'act_005', action: 'Archived Proof Pack: Lead Generation Pro Email Nurture Sequence Results', user: 'Marcus Webb', avatar: 'MW', time: '2 hours ago', type: 'archive' },
  { id: 'act_006', action: 'Created new client: Synergy Brands', user: 'Sarah Chen', avatar: 'SC', time: '4 hours ago', type: 'create' },
  { id: 'act_007', action: 'Updated campaign: Q1 2024 Conversion Boost', user: 'David Lee', avatar: 'DL', time: 'Yesterday', type: 'update' },
  { id: 'act_008', action: 'Changed status of Brand Builders Q2 Google Ads Optimization to \'review\'', user: 'Marcus Webb', avatar: 'MW', time: 'Yesterday', type: 'status-change' },
  { id: 'act_009', action: 'Generated report for Proof Pack: Future Innovations Winter Lead Gen Outcomes', user: 'Sarah Chen', avatar: 'SC', time: '2 days ago', type: 'export' },
  { id: 'act_010', action: 'Created new Proof Pack: Growth Metrics Summer Sale Promo Report', user: 'Marcus Webb', avatar: 'MW', time: '3 days ago', type: 'create' },
  { id: 'act_011', action: 'Updated Proof Pack: Synergy Brands Social Media Engagement Report', user: 'David Lee', avatar: 'DL', time: '3 days ago', type: 'update' },
  { id: 'act_012', action: 'Added new campaign: Content Marketing Strategy H2 for Alpha Marketing Group', user: 'Sarah Chen', avatar: 'SC', time: '4 days ago', type: 'create' },
];

export function getById<T extends { id: string }>(arr: T[], id: string): T | undefined {
  return arr.find(x => x.id === id);
}